// Code generated by archivist. DO NOT EDIT.

package conf

import (
	"time"

	"github.com/pkg/errors"
	"github.com/kingsgroupos/archivist/runtime/go/archivist"
	"github.com/kingsgroupos/misc/wtime"
)

var (
	_ = time.After
	_ = errors.New
	_ = archivist.NewArchivist
	_ = wtime.ParseDuration
)

// easyjson:json
type EConf struct {
	E1 int64            `json:"E1" bson:"E1"`
	E2 int64            `json:"E2" bson:"E2"`
	E3 int64            `json:"E3" bson:"E3"`
	E5 []int64          `json:"E5" bson:"E5"`
	E6 []int64          `json:"E6" bson:"E6"`
	E7 map[string]int64 `json:"E7" bson:"E7"`
	E8 map[string]int64 `json:"E8" bson:"E8"`
}

func (this *EConf) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}
