// Code generated by archivist. DO NOT EDIT.

package conf

import (
	"time"

	"github.com/pkg/errors"
	"github.com/kingsgroupos/archivist/runtime/go/archivist"
	"github.com/kingsgroupos/misc/wtime"
)

var (
	_ = time.After
	_ = errors.New
	_ = archivist.NewArchivist
	_ = wtime.ParseDuration
)

// easyjson:json
type FConf struct {
	F1 int64 `json:"F1" bson:"F1"`
	F2 int64 `json:"F2" bson:"F2"`
	F3 int64 `json:"F3" bson:"F3"`
	F5 int64 `json:"F5" bson:"F5"`
}

func (this *FConf) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}
