// Code generated by archivist. DO NOT EDIT.

package conf

import (
	"time"

	"github.com/kingsgroupos/archivist/lib/go/archivist"
	"github.com/kingsgroupos/misc/wtime"
	"github.com/pkg/errors"
)

var (
	_ = time.After
	_ = errors.New
	_ = archivist.NewArchivist
	_ = wtime.ParseDuration
)

// easyjson:json
type GithubConf struct {
	CloneUrl         string                 `json:"clone_url" bson:"clone_url"`
	CreatedAt        string                 `json:"created_at" bson:"created_at"`
	DefaultBranch    string                 `json:"default_branch" bson:"default_branch"`
	Description      string                 `json:"description" bson:"description"`
	Fork             bool                   `json:"fork" bson:"fork"`
	ForksCount       int64                  `json:"forks_count" bson:"forks_count"`
	FullName         string                 `json:"full_name" bson:"full_name"`
	GitUrl           string                 `json:"git_url" bson:"git_url"`
	HasDownloads     bool                   `json:"has_downloads" bson:"has_downloads"`
	HasIssues        bool                   `json:"has_issues" bson:"has_issues"`
	HasWiki          bool                   `json:"has_wiki" bson:"has_wiki"`
	Homepage         string                 `json:"homepage" bson:"homepage"`
	HtmlUrl          string                 `json:"html_url" bson:"html_url"`
	Id               int64                  `json:"id" bson:"_id"`
	MirrorUrl        string                 `json:"mirror_url" bson:"mirror_url"`
	Name             string                 `json:"name" bson:"name"`
	OpenIssuesCount  int64                  `json:"open_issues_count" bson:"open_issues_count"`
	Organization     *GithubConf_216391827  `json:"organization" bson:"organization"`
	Owner            *GithubConf_240645118  `json:"owner" bson:"owner"`
	Parent           *GithubConf_2003163775 `json:"parent" bson:"parent"`
	Permissions      *GithubConf_570840785  `json:"permissions" bson:"permissions"`
	Private          bool                   `json:"private" bson:"private"`
	PushedAt         string                 `json:"pushed_at" bson:"pushed_at"`
	Size             int64                  `json:"size" bson:"size"`
	Source           *GithubConf_267759930  `json:"source" bson:"source"`
	SshUrl           string                 `json:"ssh_url" bson:"ssh_url"`
	StargazersCount  int64                  `json:"stargazers_count" bson:"stargazers_count"`
	SubscribersCount int64                  `json:"subscribers_count" bson:"subscribers_count"`
	SvnUrl           string                 `json:"svn_url" bson:"svn_url"`
	UpdatedAt        string                 `json:"updated_at" bson:"updated_at"`
	Url              string                 `json:"url" bson:"url"`
	WatchersCount    int64                  `json:"watchers_count" bson:"watchers_count"`
}

// GithubConf_216391827 represents /organization
type GithubConf_216391827 struct {
	AvatarUrl         string `json:"avatar_url" bson:"avatar_url"`
	EventsUrl         string `json:"events_url" bson:"events_url"`
	FollowersUrl      string `json:"followers_url" bson:"followers_url"`
	FollowingUrl      string `json:"following_url" bson:"following_url"`
	GistsUrl          string `json:"gists_url" bson:"gists_url"`
	GravatarId        string `json:"gravatar_id" bson:"gravatar_id"`
	HtmlUrl           string `json:"html_url" bson:"html_url"`
	Id                int64  `json:"id" bson:"_id"`
	Login             string `json:"login" bson:"login"`
	OrganizationsUrl  string `json:"organizations_url" bson:"organizations_url"`
	ReceivedEventsUrl string `json:"received_events_url" bson:"received_events_url"`
	ReposUrl          string `json:"repos_url" bson:"repos_url"`
	SiteAdmin         bool   `json:"site_admin" bson:"site_admin"`
	StarredUrl        string `json:"starred_url" bson:"starred_url"`
	SubscriptionsUrl  string `json:"subscriptions_url" bson:"subscriptions_url"`
	Type              string `json:"type" bson:"type"`
	Url               string `json:"url" bson:"url"`
}

// GithubConf_240645118 represents /owner
type GithubConf_240645118 struct {
	AvatarUrl         string `json:"avatar_url" bson:"avatar_url"`
	EventsUrl         string `json:"events_url" bson:"events_url"`
	FollowersUrl      string `json:"followers_url" bson:"followers_url"`
	FollowingUrl      string `json:"following_url" bson:"following_url"`
	GistsUrl          string `json:"gists_url" bson:"gists_url"`
	GravatarId        string `json:"gravatar_id" bson:"gravatar_id"`
	HtmlUrl           string `json:"html_url" bson:"html_url"`
	Id                int64  `json:"id" bson:"_id"`
	Login             string `json:"login" bson:"login"`
	OrganizationsUrl  string `json:"organizations_url" bson:"organizations_url"`
	ReceivedEventsUrl string `json:"received_events_url" bson:"received_events_url"`
	ReposUrl          string `json:"repos_url" bson:"repos_url"`
	SiteAdmin         bool   `json:"site_admin" bson:"site_admin"`
	StarredUrl        string `json:"starred_url" bson:"starred_url"`
	SubscriptionsUrl  string `json:"subscriptions_url" bson:"subscriptions_url"`
	Type              string `json:"type" bson:"type"`
	Url               string `json:"url" bson:"url"`
}

// GithubConf_2003163775 represents /parent
type GithubConf_2003163775 struct {
	CloneUrl        string                `json:"clone_url" bson:"clone_url"`
	CreatedAt       string                `json:"created_at" bson:"created_at"`
	DefaultBranch   string                `json:"default_branch" bson:"default_branch"`
	Description     string                `json:"description" bson:"description"`
	Fork            bool                  `json:"fork" bson:"fork"`
	ForksCount      int64                 `json:"forks_count" bson:"forks_count"`
	FullName        string                `json:"full_name" bson:"full_name"`
	GitUrl          string                `json:"git_url" bson:"git_url"`
	HasDownloads    bool                  `json:"has_downloads" bson:"has_downloads"`
	HasIssues       bool                  `json:"has_issues" bson:"has_issues"`
	HasWiki         bool                  `json:"has_wiki" bson:"has_wiki"`
	Homepage        string                `json:"homepage" bson:"homepage"`
	HtmlUrl         string                `json:"html_url" bson:"html_url"`
	Id              int64                 `json:"id" bson:"_id"`
	MirrorUrl       string                `json:"mirror_url" bson:"mirror_url"`
	Name            string                `json:"name" bson:"name"`
	OpenIssuesCount int64                 `json:"open_issues_count" bson:"open_issues_count"`
	Owner           *GithubConf_433431318 `json:"owner" bson:"owner"`
	Permissions     *GithubConf_249756142 `json:"permissions" bson:"permissions"`
	Private         bool                  `json:"private" bson:"private"`
	PushedAt        string                `json:"pushed_at" bson:"pushed_at"`
	Size            int64                 `json:"size" bson:"size"`
	SshUrl          string                `json:"ssh_url" bson:"ssh_url"`
	StargazersCount int64                 `json:"stargazers_count" bson:"stargazers_count"`
	SvnUrl          string                `json:"svn_url" bson:"svn_url"`
	UpdatedAt       string                `json:"updated_at" bson:"updated_at"`
	Url             string                `json:"url" bson:"url"`
	WatchersCount   int64                 `json:"watchers_count" bson:"watchers_count"`
}

// GithubConf_433431318 represents /parent/owner
type GithubConf_433431318 struct {
	AvatarUrl         string `json:"avatar_url" bson:"avatar_url"`
	EventsUrl         string `json:"events_url" bson:"events_url"`
	FollowersUrl      string `json:"followers_url" bson:"followers_url"`
	FollowingUrl      string `json:"following_url" bson:"following_url"`
	GistsUrl          string `json:"gists_url" bson:"gists_url"`
	GravatarId        string `json:"gravatar_id" bson:"gravatar_id"`
	HtmlUrl           string `json:"html_url" bson:"html_url"`
	Id                int64  `json:"id" bson:"_id"`
	Login             string `json:"login" bson:"login"`
	OrganizationsUrl  string `json:"organizations_url" bson:"organizations_url"`
	ReceivedEventsUrl string `json:"received_events_url" bson:"received_events_url"`
	ReposUrl          string `json:"repos_url" bson:"repos_url"`
	SiteAdmin         bool   `json:"site_admin" bson:"site_admin"`
	StarredUrl        string `json:"starred_url" bson:"starred_url"`
	SubscriptionsUrl  string `json:"subscriptions_url" bson:"subscriptions_url"`
	Type              string `json:"type" bson:"type"`
	Url               string `json:"url" bson:"url"`
}

// GithubConf_249756142 represents /parent/permissions
type GithubConf_249756142 struct {
	Admin bool `json:"admin" bson:"admin"`
	Pull  bool `json:"pull" bson:"pull"`
	Push  bool `json:"push" bson:"push"`
}

// GithubConf_570840785 represents /permissions
type GithubConf_570840785 struct {
	Admin bool `json:"admin" bson:"admin"`
	Pull  bool `json:"pull" bson:"pull"`
	Push  bool `json:"push" bson:"push"`
}

// GithubConf_267759930 represents /source
type GithubConf_267759930 struct {
	CloneUrl        string                 `json:"clone_url" bson:"clone_url"`
	CreatedAt       string                 `json:"created_at" bson:"created_at"`
	DefaultBranch   string                 `json:"default_branch" bson:"default_branch"`
	Description     string                 `json:"description" bson:"description"`
	Fork            bool                   `json:"fork" bson:"fork"`
	ForksCount      int64                  `json:"forks_count" bson:"forks_count"`
	FullName        string                 `json:"full_name" bson:"full_name"`
	GitUrl          string                 `json:"git_url" bson:"git_url"`
	HasDownloads    bool                   `json:"has_downloads" bson:"has_downloads"`
	HasIssues       bool                   `json:"has_issues" bson:"has_issues"`
	HasWiki         bool                   `json:"has_wiki" bson:"has_wiki"`
	Homepage        string                 `json:"homepage" bson:"homepage"`
	HtmlUrl         string                 `json:"html_url" bson:"html_url"`
	Id              int64                  `json:"id" bson:"_id"`
	MirrorUrl       string                 `json:"mirror_url" bson:"mirror_url"`
	Name            string                 `json:"name" bson:"name"`
	OpenIssuesCount int64                  `json:"open_issues_count" bson:"open_issues_count"`
	Owner           *GithubConf_229071146  `json:"owner" bson:"owner"`
	Permissions     *GithubConf_2094552156 `json:"permissions" bson:"permissions"`
	Private         bool                   `json:"private" bson:"private"`
	PushedAt        string                 `json:"pushed_at" bson:"pushed_at"`
	Size            int64                  `json:"size" bson:"size"`
	SshUrl          string                 `json:"ssh_url" bson:"ssh_url"`
	StargazersCount int64                  `json:"stargazers_count" bson:"stargazers_count"`
	SvnUrl          string                 `json:"svn_url" bson:"svn_url"`
	UpdatedAt       string                 `json:"updated_at" bson:"updated_at"`
	Url             string                 `json:"url" bson:"url"`
	WatchersCount   int64                  `json:"watchers_count" bson:"watchers_count"`
}

// GithubConf_229071146 represents /source/owner
type GithubConf_229071146 struct {
	AvatarUrl         string `json:"avatar_url" bson:"avatar_url"`
	EventsUrl         string `json:"events_url" bson:"events_url"`
	FollowersUrl      string `json:"followers_url" bson:"followers_url"`
	FollowingUrl      string `json:"following_url" bson:"following_url"`
	GistsUrl          string `json:"gists_url" bson:"gists_url"`
	GravatarId        string `json:"gravatar_id" bson:"gravatar_id"`
	HtmlUrl           string `json:"html_url" bson:"html_url"`
	Id                int64  `json:"id" bson:"_id"`
	Login             string `json:"login" bson:"login"`
	OrganizationsUrl  string `json:"organizations_url" bson:"organizations_url"`
	ReceivedEventsUrl string `json:"received_events_url" bson:"received_events_url"`
	ReposUrl          string `json:"repos_url" bson:"repos_url"`
	SiteAdmin         bool   `json:"site_admin" bson:"site_admin"`
	StarredUrl        string `json:"starred_url" bson:"starred_url"`
	SubscriptionsUrl  string `json:"subscriptions_url" bson:"subscriptions_url"`
	Type              string `json:"type" bson:"type"`
	Url               string `json:"url" bson:"url"`
}

// GithubConf_2094552156 represents /source/permissions
type GithubConf_2094552156 struct {
	Admin bool `json:"admin" bson:"admin"`
	Pull  bool `json:"pull" bson:"pull"`
	Push  bool `json:"push" bson:"push"`
}

func (this *GithubConf) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok
	if err := this.Organization.bindRefs(c); err != nil {
		return err
	}
	if err := this.Owner.bindRefs(c); err != nil {
		return err
	}
	if err := this.Parent.bindRefs(c); err != nil {
		return err
	}
	if err := this.Permissions.bindRefs(c); err != nil {
		return err
	}
	if err := this.Source.bindRefs(c); err != nil {
		return err
	}

	return nil
}

func (this *GithubConf_216391827) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}

func (this *GithubConf_240645118) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}

func (this *GithubConf_2003163775) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok
	if err := this.Owner.bindRefs(c); err != nil {
		return err
	}
	if err := this.Permissions.bindRefs(c); err != nil {
		return err
	}

	return nil
}

func (this *GithubConf_433431318) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}

func (this *GithubConf_249756142) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}

func (this *GithubConf_570840785) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}

func (this *GithubConf_267759930) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok
	if err := this.Owner.bindRefs(c); err != nil {
		return err
	}
	if err := this.Permissions.bindRefs(c); err != nil {
		return err
	}

	return nil
}

func (this *GithubConf_229071146) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}

func (this *GithubConf_2094552156) bindRefs(c *Collection) error {
	if this == nil {
		return nil
	}

	var ok bool
	_ = ok

	return nil
}
