// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package conf

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA4726a31DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(in *jlexer.Lexer, out *AConf) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "A1":
			out.A1 = int64(in.Int64())
		case "A2":
			out.A2 = int64(in.Int64())
		case "A3":
			out.A3 = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA4726a31EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(out *jwriter.Writer, in AConf) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"A1\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.A1))
	}
	{
		const prefix string = ",\"A2\":"
		out.RawString(prefix)
		out.Int64(int64(in.A2))
	}
	{
		const prefix string = ",\"A3\":"
		out.RawString(prefix)
		out.Int64(int64(in.A3))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AConf) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA4726a31EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AConf) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA4726a31EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AConf) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA4726a31DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AConf) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA4726a31DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(l, v)
}
