// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package conf

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson70a7cad3DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(in *jlexer.Lexer, out *CConf) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "C1":
			out.C1 = int64(in.Int64())
		case "C2":
			out.C2 = int64(in.Int64())
		case "C3":
			out.C3 = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70a7cad3EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(out *jwriter.Writer, in CConf) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"C1\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.C1))
	}
	{
		const prefix string = ",\"C2\":"
		out.RawString(prefix)
		out.Int64(int64(in.C2))
	}
	{
		const prefix string = ",\"C3\":"
		out.RawString(prefix)
		out.Int64(int64(in.C3))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CConf) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson70a7cad3EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CConf) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson70a7cad3EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CConf) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson70a7cad3DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CConf) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson70a7cad3DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(l, v)
}
