// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package conf

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson96578744DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(in *jlexer.Lexer, out *DConf) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "D1":
			out.D1 = int64(in.Int64())
		case "D2":
			out.D2 = int64(in.Int64())
		case "D3":
			out.D3 = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson96578744EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(out *jwriter.Writer, in DConf) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"D1\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.D1))
	}
	{
		const prefix string = ",\"D2\":"
		out.RawString(prefix)
		out.Int64(int64(in.D2))
	}
	{
		const prefix string = ",\"D3\":"
		out.RawString(prefix)
		out.Int64(int64(in.D3))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DConf) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson96578744EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DConf) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson96578744EncodeGithubComKingsgrouposArchivistLibGoOverwriteConf(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DConf) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson96578744DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DConf) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson96578744DecodeGithubComKingsgrouposArchivistLibGoOverwriteConf(l, v)
}
